// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsuoseezgicejjayrtce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzdW9zZWV6Z2ljZWpqYXlydGNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTkwMTAsImV4cCI6MjA2MDYzNTAxMH0.OlXg9Vr3I0-J2k0IGqRkEqw0_UL24jN5H53CsjaN9Cs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);